volumes:
  postgres_wiki_test_data: {}
  postgres_wiki_test_data_backups: {}
  redis_wiki_test_data: {}

services:
  django_wiki_test: &django_wiki_test
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_wiki_test
    container_name: django_wiki_test
    depends_on:
      - postgres_wiki_test
      - redis_wiki_test
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.test/.django
      - ./.envs/.test/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres_wiki_test:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: postgres_wiki_test
    container_name: postgres_wiki_test
    volumes:
      - postgres_wiki_test_data:/var/lib/postgresql/data
      - postgres_wiki_test_data_backups:/backups
    env_file:
      - ./.envs/.test/.postgres

  redis_wiki_test:
    image: docker.io/redis:6
    container_name: redis_wiki_test

    volumes:
      - redis_wiki_test_data:/data


  celeryworker_wiki_test:
    <<: *django_wiki_test
    image: celeryworker_wiki_test
    container_name: celeryworker_wiki_test
    depends_on:
      - redis_wiki_test
      - postgres_wiki_test
    ports: []
    command: /start-celeryworker

  celerybeat_wiki_test:
    <<: *django_wiki_test
    image: celerybeat_wiki_test
    container_name: celerybeat_wiki_test
    depends_on:
      - redis_wiki_test
      - postgres_wiki_test
    ports: []
    command: /start-celerybeat

  flower_wiki_test:
    <<: *django_wiki_test
    image: flower_wiki_test
    container_name: flower_wiki_test
    ports:
      - '5555:5555'
    command: /start-flower
