databases:
  - name: wiki_game
    plan: free
    databaseName: wiki_game
    user: wiki_game

services:
  - type: web
    plan: free
    name: wiki_game
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn wiki_game.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wiki_game
          property: connectionString
      - key: CELERY_BROKER_URL
        value: redis://red-cr8nrc5svqrc739d3ib0:6379/0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: REDIS_URL
        value: redis://red-cr8nrc5svqrc739d3ib0:6379/0
