services:
  - type: web
    name: wiki_game
    env: python
    buildCommand: "docker-compose -f docker-compose.local.yml build"
    startCommand: "docker-compose -f docker-compose.local.yml up"
    plan: free
    region: us-east
